spring:
  datasource:
    url: jdbc:mysql://localhost:3306?sample
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true